### ISSUE TITLE
"Production" usage examples

### ISSUE THREAD

**Issue by Goutte** [aphex/leap-cursor-library.js#1]
First of all, thanks for this ! I found the pointables' default CSS  really ingenious, btw.

What about a list of "real-life" usages in the wiki/doc ?

I'd be delighted to add the [latest airspace submission of Cyx](http://antoine.goutenoir.com/games/cyx/airspace.html) !

---

Have you thought about automated testing with Jasmine ?

**Comment by aphex** [comment]
Sounds like a great idea, I didn't even realize someone had used it for something like that. Awesome! I will throw together a wiki page soon enough.

Probably wise to add some tests to this, just haven't got around to it yet. If you happen to be a jasmine pro I would be all for accepting pulls :)

**Comment by Goutte** [comment]
I'm no Jasmine pro, but I've been digging a bit into mocking the Leap and fixturing motions ; this needs to be taken mainstream, and it looks like it'll be quite a bundle of work ! I think it can be done, though ; I was not sure at first.

I'll keep you updated !
