### ISSUE TITLE
Firefox and MouseEvent.initMouseEvent

### ISSUE THREAD

**Issue by Goutte** [aphex/leap-cursor-library.js#12]
Hello ! Good job on this lib !

On Firefox 26 on a Debian-based machine, I get :

```
TypeError: Argument 15 of MouseEvent.initMouseEvent does not implement interface EventTarget.
```

The incriminated line :

``` javascript
mouseEvent.initMouseEvent("mouseover", true, false, window, 1, this.icon.getX(), this.icon.getY(), this.icon.getX(), this.icon.getY(), false, false, false, false, 0, this.element);
```

---

As a side note, is there a reason as to why is the third argument of all `initMouseEvent` calls is `false` ?
This prevents us from calling `event.preventDefault()` in listeners, which is annoying.

**Comment by Goutte** [comment]
I tried this, **to no avail** :

``` javascript
LeapElement.prototype = {
    addEventListener: function() {
      return this.element.addEventListener.apply(this.element, arguments)
    },
    removeEventListener: function() {
      return this.element.removeEventListener.apply(this.element, arguments)
    },
    dispatchEvent: function() {
      return this.element.dispatchEvent.apply(this.element, arguments)
    },

    // also added these two for good measure

    getEventHandler: function() {
      return this.element.getEventHandler.apply(this.element, arguments)
    },
    setEventHandler: function() {
      return this.element.setEventHandler.apply(this.element, arguments)
    },

    // ...

}
```

These are methods I found on the [EventTarget](https://developer.mozilla.org/fr/docs/Web/API/EventTarget) API documentation. Maybe I'm just doing it wrong... 'tis a bit weird to talk about _interfaces_ in _javascript_.

**Comment by Goutte** [comment]
Of course, fixing up the `initMouseEvent` lines by passing `this.element.element` instead of `this.element` seems to do the trick :

``` javascript
mouseEvent.initMouseEvent("mouseover", true, false, window, 1, this.icon.getX(), this.icon.getY(), this.icon.getX(), this.icon.getY(), false, false, false, false, 0, this.element.element);
```

Yet, I'd rather understand why (oh why ?) adding the methods is not enough.
Interfaces in Javascript... :weary:

**Comment by Goutte** [comment]
Unrelated, but when using a single cursor, `hand.palmPosition` provides a shake-free and more consistent data, as seen on the latest (as in ten minutes ago) version of [Cyx](http://antoine.goutenoir.com/games/cyx/).

**Comment by aphex** [comment]
Not gonna lie I pretty much live in Chrome so any FireFox help would be awesome. If you want to submit a PR fixing up all the initMouseEvent calls with the proper element that would be great. 

Also Maybe open a new issue for palmPosition, we can have a discussion there maybe we just pass in a flag "usePalm" and that will override everything and only give you one cursor based on the palm.

**Comment by Goutte** [comment]
There you go !

Any thoughts about that `cancelable` third parameter ?
I'm all for setting it to `true` :+1:

**Comment by aphex** [comment]
:+1: to cancelable, lets do it

**Comment by Goutte** [comment]
Done in PR #15
