### ISSUE TITLE
Using `Hand.palmPosition`

### ISSUE THREAD

**Issue by Goutte** [aphex/leap-cursor-library.js#14]
`Hand.palmPosition` provides consistent data. More consistent than the `Pointables`.

We have at least two solutions :

1/ Make it the default input when `maxCursors == 1`. No extra configuration needed to provide a smoother experience.
2/ Create a `usePalms` or `useHands` or `trackPalmsOnly` boolean option. Extra configuration, but would allow for multiple hand-cursors (i don't know if the Leap can track more than two)

**Comment by aphex** [comment]
hmm I like the idea of usePalms, as it is also a pretty likely situation for someone to just want one finger cursor. Mainly because they want to do finger gestures like tap and circle and such. 

I am thinking when usePalms is true maxCursors defaults to 2 and the only other option is 1.

**Comment by Goutte** [comment]
Oh, I forgot about the gestures !

:+1:

**Comment by aphex** [comment]
Added useHands (hands is the name leap is using so I stuck with it)
Added Grab gesture when using hands.
New Demos added also

https://github.com/aphex/leap-cursor-library.js/commit/83418fbb909d2d7d08b77015d6fa9c61c6a6fc3f
