### ISSUE TITLE
Leapstrap - HTML5 Framework for Leap

### ISSUE THREAD

**Issue by wilkesalex** [aphex/leap-cursor-library.js#2]
Hi aphex

I am making use of leap-cursor-library.js in Leapstrap

http://wilkesalex.github.io/leapstrap/

Leapstrap is a ready-to-use HTML5 framework for touch. It is based on Twitter Bootstrap.

As you can see I commented and documented some of your library's functions

http://wilkesalex.github.io/leapstrap/leap/

Let me know if you want to collaborate, your code is really cool.

Cheers
Alex

**Comment by aphex** [comment]
Nice! The comments will be very helpful. Good idea overall
