### ISSUE TITLE
basic-presscroll has broken links

### ISSUE THREAD

**Issue by bingomanatee** [aphex/leap-cursor-library.js#3]
examples/basic-pressscroll.html

has broken links

http://sc13-live.sencha.com/touch/touch-2.3.0/sencha-touch-all.js
http://sc13-live.sencha.com/touch/touch-2.3.0/resources/css/sencha-touch.css
404

**Comment by bingomanatee** [comment]
may be a problem wth sencha api itself

**Comment by jhannah** [comment]
Fixed in #6
