### ISSUE TITLE
Custom large image "cursor"

### ISSUE THREAD

**Issue by jhannah** [aphex/leap-cursor-library.js#4]
Is there an easy way to use a custom image as the cursor? e.g. /images/mycursor.png

**Comment by aphex** [comment]
Sure its all done with CSS, you can check out the manager SCSS file and tweak it, or simply provide your own CSS file and take over the styles.

**Comment by jhannah** [comment]
Hmm... But CSS cursors can only be 128x128 pixels (32x32 for maximum compatibility), right? I'm wanting to drag larger images around as the "cursor." So I guess I'm going to need to attach a div with an image... Was wondering if leap-cursor-library.js had anything for this already.

**Comment by aphex** [comment]
A leap cursor is a div. All of them share a class you can target to make look like whatever you wish.

**Comment by jhannah** [comment]
Oh? 

If I hack `leap-manager.js dispatchMove()` to move my own `<div><img></div>` around then I get the effect I'm looking for. 

But I'm not sure which div you're referring to, nor how I would add an img to it. My first attempt looked like this, which didn't seem to get me anywhere:

```
LeapManager.init({
    maxCursors:1,
    interactiveSelector: ".item"
});
var elem = document.createElement("img");
elem.setAttribute("src", "images/mycursor.png");
document.getElementById("leap-cursor-container").appendChild(elem);
```

Thanks :)

**Comment by aphex** [comment]
Are you not seeing the circle cursors on the screen when you just do an init? if you only have this

```
LeapManager.init({
    maxCursors:1,
    interactiveSelector: ".item"
});
```

You should see a single circle cursor on the screen. Are you including the CSS that comes with the library. you should be able to just add a background image to the class selector and all the cursors will be images.

**Comment by jhannah** [comment]
Yes, the default circle cursors work fine.
Sorry, I don't know how to "add a background image to the class selector." As you can see, I suck at front end dev. :)

**Comment by aphex** [comment]
Ahh ok. Well first can you confirm you are seeing the Circle the represents your cursor currently? 

If you want to style the cursor add your own CSS file. so open your index.html file and just underneath the <link> tag that loads the leap-manager.css

```
<link rel="stylesheet" type="text/css" href="path/to/custom.css">
```

You could also just add a style tag inside the index.html head tag and write all your custom styles in there. Should work regardless. 

Inside that file you will want to style the leap-cursor class like this

```
.leap-cursor {
background-image: url('path/to/image.png');
width:100px;
height:100px;
}
```

I would google around for CSS styling to get some more info on how to customize the look of html.

**Comment by jhannah** [comment]
Ah, yup! Looks like the only CSS I need is this, and everything works:

```
.leap-cursor {
    position: absolute;
    transition-property: background-color; 
    background-image: url('images/myimage.png');
    width:300px;
    height:300px;
}
```

Thanks! Happy new year! (Next I'm going to make the image zoom in / out based on Leap z position. :) )
