### ISSUE TITLE
Access to Leap.loop() frames

### ISSUE THREAD

**Issue by jhannah** [aphex/leap-cursor-library.js#8]
`leap-manager.js` wraps `Leap.loop()`, which is usually great. Usually I don't have to know or care what `loop()` does. 

But I find myself wanting to do arbitrary additional things based on the Leap `frame` objects. Unfortunately once I use `leap-manager.js` I no longer have access to the `frame` objects. Do I?

**Comment by jhannah** [comment]
(My specific use case is that I'd like to resize my custom image "cursor" from `/examples/image-cursor.html` (#7) based on Leap `frame.pointables[0].tipPosition[2]`.)

**Comment by aphex** [comment]
I am all for this but I think we should also add a cursor variable to ever mousevent that is dispatched via a cursor. I will fix this up right now, this will allow you to just listen to mouseMove on your body. you can then check the event for a cursor variable and get any (x, y or z) properties of the cursor. 

I think this would be better the polling the pointables array manually

**Comment by jhannah** [comment]
Cool! Let me know when that is available. :+1: :)

**Comment by jhannah** [comment]
Oh! Don't let me forget that we need to update `lib/js/leap.min.js` now that `src/js/leap-manager.js` has changed. I won't bother doing it now since you're making the above changes anyway. Thanks. :)

**Comment by aphex** [comment]
All updated

**Comment by jhannah** [comment]
Thanks! Do your new events deprecate [my use of frameCallback](https://github.com/iinteractive/leap-cursor-library.js/blob/cursor-zoom/examples/image-cursor.html)?

**Comment by aphex** [comment]
Nah, I think it's good to allow people to access that also.

**Comment by jhannah** [comment]
Sure, that's cool. I was just checking to see if my use of frameCallback above still makes sense in the light of the new event code you just added.

**Comment by aphex** [comment]
Not sure there is a "right" way I would probably do it with a move event listener and the cursor Just and organization thing.
